-- 1. Categories 表 (分类)
create table categories (
                            id bigint generated by default as identity primary key,
                            name text not null,
                            position integer not null default 0,
                            parent_id bigint references categories(id) on delete cascade,
                            depth integer not null default 0,
                            is_private boolean default false, -- 改为布尔类型
                            created_at timestamp with time zone default timezone('utc'::text, now()) not null,
                            unique(name, parent_id)
);

-- 2. Bookmarks 表 (书签)
create table bookmarks (
                           id bigint generated by default as identity primary key,
                           name text not null,
                           url text not null,
                           description text,
                           icon text,
                           category_id bigint not null references categories(id) on delete cascade,
                           position integer not null default 0,
                           is_private boolean default false, -- 改为布尔类型
                           created_at timestamp with time zone default timezone('utc'::text, now()) not null,
                           updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Settings 表 (设置)
create table settings (
                          id bigint generated by default as identity primary key,
                          key text not null unique,
                          value text not null,
                          created_at timestamp with time zone default timezone('utc'::text, now()) not null,
                          updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. 创建索引 (提升性能)
create index if not exists idx_bookmarks_category_position on bookmarks(category_id, position);
create index if not exists idx_bookmarks_private on bookmarks(is_private);
create index if not exists idx_bookmarks_url on bookmarks(url);
create index if not exists idx_categories_position on categories(position);
create index if not exists idx_categories_parent_id on categories(parent_id);
create index if not exists idx_categories_parent_position on categories(parent_id, position);
create index if not exists idx_categories_private on categories(is_private);
create index if not exists idx_settings_key on settings(key);

-- 5. 开启 RLS 安全策略 (重要！)
alter table categories enable row level security;
alter table bookmarks enable row level security;
alter table settings enable row level security;

-- 策略 A: 允许所有人读取“非私有”的数据 (用于公开展示)
create policy "Public Read Categories" on categories for select using (is_private = false);
create policy "Public Read Bookmarks" on bookmarks for select using (is_private = false);
-- settings 表通常包含敏感配置，默认不公开，或者你可以指定公开某些 key

-- 策略 B: 允许“登录用户”进行所有操作 (增删改查)
-- 只有当你登录后 (Supabase Auth)，才能修改数据或查看私有数据
create policy "Authenticated Full Access Categories" on categories for all using (auth.role() = 'authenticated');
create policy "Authenticated Full Access Bookmarks" on bookmarks for all using (auth.role() = 'authenticated');
create policy "Authenticated Full Access Settings" on settings for all using (auth.role() = 'authenticated');