-- ==========================================
-- 1. 建表 (直接包含 user_id 字段)
-- ==========================================

-- 分类表
create table categories (
                            id bigint generated by default as identity primary key,
                            user_id uuid references auth.users(id) default auth.uid(), -- 关联用户ID
                            name text not null,
                            position integer not null default 0,
                            parent_id bigint references categories(id) on delete cascade,
                            depth integer not null default 0,
                            is_private boolean default false,
                            created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    -- 确保同一用户下的同级分类不重名，不同用户可以重名
                            unique(user_id, name, parent_id)
);

-- 书签表
create table bookmarks (
                           id bigint generated by default as identity primary key,
                           user_id uuid references auth.users(id) default auth.uid(), -- 关联用户ID
                           name text not null,
                           url text not null,
                           description text,
                           icon text,
                           category_id bigint not null references categories(id) on delete cascade,
                           position integer not null default 0,
                           is_private boolean default false,
                           created_at timestamp with time zone default timezone('utc'::text, now()) not null,
                           updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 设置表
create table settings (
                          id bigint generated by default as identity primary key,
                          user_id uuid references auth.users(id) default auth.uid(), -- 关联用户ID
                          key text not null,
                          value text not null,
                          created_at timestamp with time zone default timezone('utc'::text, now()) not null,
                          updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    -- 确保每个用户的设置 key 是唯一的
                          unique(user_id, key)
);

-- ==========================================
-- 2. 创建索引 (优化查询速度)
-- ==========================================

-- 书签查询优化
create index idx_bookmarks_user_id on bookmarks(user_id);
create index idx_bookmarks_category_id on bookmarks(category_id);
create index idx_bookmarks_position on bookmarks(category_id, position);

-- 分类查询优化
create index idx_categories_user_id on categories(user_id);
create index idx_categories_parent_id on categories(parent_id);
create index idx_categories_position on categories(position);

-- 设置查询优化
create index idx_settings_user_key on settings(user_id, key);

-- ==========================================
-- 3. 开启 RLS (行级安全)
-- ==========================================
alter table categories enable row level security;
alter table bookmarks enable row level security;
alter table settings enable row level security;

-- ==========================================
-- 4. 配置 RLS 策略 (核心隔离逻辑)
-- ==========================================

-- 策略：用户只能 查看/修改/删除 user_id 等于自己 UID 的数据
-- 注意：不再创建任何 "Public Read" 策略，确保完全隔离

-- Categories
create policy "Users can only access their own categories" on categories
  for all using (auth.uid() = user_id);

-- Bookmarks
create policy "Users can only access their own bookmarks" on bookmarks
  for all using (auth.uid() = user_id);

-- Settings
create policy "Users can only access their own settings" on settings
  for all using (auth.uid() = user_id);

-- ==========================================
-- 5. 配置自动填充 Trigger (双重保险)
-- ==========================================

-- 创建一个函数，用于在插入数据时自动填入当前用户的 UID
create or replace function public.handle_new_record()
                                   returns trigger as $$
begin
    new.user_id := auth.uid();
return new;
end;
$$ language plpgsql security definer;

-- 将函数绑定到三张表的 INSERT 操作上
create trigger set_categories_userid before insert on categories
    for each row execute function public.handle_new_record();

create trigger set_bookmarks_userid before insert on bookmarks
    for each row execute function public.handle_new_record();

create trigger set_settings_userid before insert on settings
    for each row execute function public.handle_new_record();